### ISSUE TITLE
Failing when using django-tenant-schemas

### ISSUE THREAD

**Issue by kingbuzzman** [mypebble/django-pgviews#50]
django-pgviews always assumes that there will be only one schema `public` and that all the tables/views will belong to it. When using multiple schemas, see: https://github.com/bernardopires/django-tenant-schemas -- views that belong to a tenant fail on App.ready().

```
Traceback (most recent call last):
  File "/var/www/student-platform/student-platform/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 42, in handle
    executor.run_migrations(tenants=[self.schema_name])
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 58, in run_migrations
    run_migrations(self.args, self.options, self.codename, public_schema_name)
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 31, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 257, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/var/www/student-platform/student-platform/django_pgviews/apps.py", line 29, in sync_pgviews
    vs.run(force=True, update=True)
  File "/var/www/student-platform/student-platform/django_pgviews/models.py", line 25, in run
    backlog = self.run_backlog(backlog, force, update)
  File "/var/www/student-platform/student-platform/django_pgviews/models.py", line 56, in run_backlog
    index=view_cls._concurrent_index)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/www/student-platform/student-platform/django_pgviews/view.py", line 121, in create_view
    cursor.execute('CREATE OR REPLACE VIEW {0} AS {1};'.format(view_name, view_query))
psycopg2.ProgrammingError: relation "xxxxxxxxx" does not exist
LINE 11:           FROM xxxxxxxxx
```

**Comment by kingbuzzman** [comment]
Project is dead.

**Comment by mikicz** [comment]
I'm maintaining a fork at https://github.com/mikicz/django-pgviews, https://pypi.org/project/django-pgviews-redux/
